name: CI

on:
    workflow_call:
        inputs:
            checks:
                description: "JSON array of npm scripts to run"
                type: string
                required: true

jobs:
    ci:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                check: ${{ fromJSON(inputs.checks) }}
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run check
              run: npm run ${{ matrix.check }}
